# Generated by Django 4.0.6 on 2022-07-14 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='priorities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_priority', models.TextField(max_length=50)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=100)),
                ('last_name', models.TextField(max_length=100)),
                ('email_address', models.EmailField(max_length=100, null=True)),
                ('login', models.TextField(max_length=100)),
                ('password', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_task', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('date', models.DateField()),
                ('is_execute', models.BooleanField()),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authapp.priorities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.users')),
            ],
        ),
    ]
